package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Obsidian Theme (Default Luxury Dark)
val ObsidianBg = Color(0xFF07080B)
val ObsidianSurface = Color(0xFF101217)
val ObsidianSurfaceElevated = Color(0xFF181B22)
val ObsidianCardBorder = Color(0xFF262B35)
val ObsidianPrimary = Color(0xFFE5B54F) // Muted luxury gold
val ObsidianAccent = Color(0xFF38BDF8)  // Cinema cyan
val ObsidianTextPrimary = Color(0xFFF3F4F6)
val ObsidianTextSecondary = Color(0xFF9CA3AF)

// Midnight Theme
val MidnightBg = Color(0xFF060B14)
val MidnightSurface = Color(0xFF0C1424)
val MidnightSurfaceElevated = Color(0xFF132038)
val MidnightCardBorder = Color(0xFF1E3A5F)
val MidnightPrimary = Color(0xFF38BDF8)
val MidnightAccent = Color(0xFF818CF8)

// Graphite Theme
val GraphiteBg = Color(0xFF101012)
val GraphiteSurface = Color(0xFF1A1A1E)
val GraphiteSurfaceElevated = Color(0xFF24242A)
val GraphiteCardBorder = Color(0xFF34343D)
val GraphitePrimary = Color(0xFFF4F4F5)
val GraphiteAccent = Color(0xFFA1A1AA)

// Pearl Theme (Luxury Light)
val PearlBg = Color(0xFFF8F9FA)
val PearlSurface = Color(0xFFFFFFFF)
val PearlSurfaceElevated = Color(0xFFF1F3F5)
val PearlCardBorder = Color(0xFFE9ECEF)
val PearlPrimary = Color(0xFFB4833E)
val PearlAccent = Color(0xFF0284C7)
val PearlTextPrimary = Color(0xFF111827)
val PearlTextSecondary = Color(0xFF6B7280)

// Frost Theme (Cool Light)
val FrostBg = Color(0xFFF0F4F8)
val FrostSurface = Color(0xFFFFFFFF)
val FrostSurfaceElevated = Color(0xFFE2E8F0)
val FrostCardBorder = Color(0xFFCBD5E1)
val FrostPrimary = Color(0xFF0284C7)
val FrostAccent = Color(0xFF6366F1)

// Aurora Theme (Cinema Studio)
val AuroraBg = Color(0xFF06100D)
val AuroraSurface = Color(0xFF0C1D18)
val AuroraSurfaceElevated = Color(0xFF132D25)
val AuroraCardBorder = Color(0xFF1D4538)
val AuroraPrimary = Color(0xFF10B981)
val AuroraAccent = Color(0xFFA855F7)

// --- Pastel Themes ---

// 1. Pastel Rose (Blush Quartz)
val PastelRoseLightBg = Color(0xFFFFF5F7)
val PastelRoseLightSurface = Color(0xFFFFFFFF)
val PastelRoseLightElevated = Color(0xFFFDE8EC)
val PastelRoseLightBorder = Color(0xFFFBCFE8)
val PastelRoseLightPrimary = Color(0xFFEC4899)
val PastelRoseLightAccent = Color(0xFFFB7185)
val PastelRoseLightText = Color(0xFF4A1525)
val PastelRoseLightTextSec = Color(0xFF9D4C68)

val PastelRoseDarkBg = Color(0xFF1F1016)
val PastelRoseDarkSurface = Color(0xFF2D1620)
val PastelRoseDarkElevated = Color(0xFF3B1D2A)
val PastelRoseDarkBorder = Color(0xFF5E273F)
val PastelRoseDarkPrimary = Color(0xFFF472B6)
val PastelRoseDarkAccent = Color(0xFFFDA4AF)
val PastelRoseDarkText = Color(0xFFFFF1F2)
val PastelRoseDarkTextSec = Color(0xFFE2A8B8)

// 2. Pastel Lavender (Lilac Mist)
val PastelLavenderLightBg = Color(0xFFF8F5FF)
val PastelLavenderLightSurface = Color(0xFFFFFFFF)
val PastelLavenderLightElevated = Color(0xFFEDE5FF)
val PastelLavenderLightBorder = Color(0xFFDDD6FE)
val PastelLavenderLightPrimary = Color(0xFF8B5CF6)
val PastelLavenderLightAccent = Color(0xFFA78BFA)
val PastelLavenderLightText = Color(0xFF2E1065)
val PastelLavenderLightTextSec = Color(0xFF7C6E9E)

val PastelLavenderDarkBg = Color(0xFF141020)
val PastelLavenderDarkSurface = Color(0xFF1E182E)
val PastelLavenderDarkElevated = Color(0xFF2A223E)
val PastelLavenderDarkBorder = Color(0xFF433566)
val PastelLavenderDarkPrimary = Color(0xFFA78BFA)
val PastelLavenderDarkAccent = Color(0xFFC084FC)
val PastelLavenderDarkText = Color(0xFFFAF5FF)
val PastelLavenderDarkTextSec = Color(0xFFC4B5FD)

// 3. Pastel Mint (Sage Breeze)
val PastelMintLightBg = Color(0xFFF2FBF7)
val PastelMintLightSurface = Color(0xFFFFFFFF)
val PastelMintLightElevated = Color(0xFFE1F7EC)
val PastelMintLightBorder = Color(0xFFA7F3D0)
val PastelMintLightPrimary = Color(0xFF10B981)
val PastelMintLightAccent = Color(0xFF34D399)
val PastelMintLightText = Color(0xFF064E3B)
val PastelMintLightTextSec = Color(0xFF047857)

val PastelMintDarkBg = Color(0xFF0C1914)
val PastelMintDarkSurface = Color(0xFF142720)
val PastelMintDarkElevated = Color(0xFF1C362C)
val PastelMintDarkBorder = Color(0xFF2E5B4B)
val PastelMintDarkPrimary = Color(0xFF6EE7B7)
val PastelMintDarkAccent = Color(0xFF5EEAD4)
val PastelMintDarkText = Color(0xFFECFDF5)
val PastelMintDarkTextSec = Color(0xFFA7F3D0)

// 4. Pastel Peach (Apricot Glow)
val PastelPeachLightBg = Color(0xFFFFF7F2)
val PastelPeachLightSurface = Color(0xFFFFFFFF)
val PastelPeachLightElevated = Color(0xFFFFE8DC)
val PastelPeachLightBorder = Color(0xFFFED7AA)
val PastelPeachLightPrimary = Color(0xFFF97316)
val PastelPeachLightAccent = Color(0xFFFB923C)
val PastelPeachLightText = Color(0xFF7C2D12)
val PastelPeachLightTextSec = Color(0xFFC2410C)

val PastelPeachDarkBg = Color(0xFF1D120B)
val PastelPeachDarkSurface = Color(0xFF2C1B11)
val PastelPeachDarkElevated = Color(0xFF3C2417)
val PastelPeachDarkBorder = Color(0xFF5D3925)
val PastelPeachDarkPrimary = Color(0xFFFDBA74)
val PastelPeachDarkAccent = Color(0xFFFFEDD5)
val PastelPeachDarkText = Color(0xFFFFF7ED)
val PastelPeachDarkTextSec = Color(0xFFFDBA74)

// 5. Pastel Sky (Powder Blue)
val PastelSkyLightBg = Color(0xFFF0F8FF)
val PastelSkyLightSurface = Color(0xFFFFFFFF)
val PastelSkyLightElevated = Color(0xFFE0F2FE)
val PastelSkyLightBorder = Color(0xFFBAE6FD)
val PastelSkyLightPrimary = Color(0xFF0284C7)
val PastelSkyLightAccent = Color(0xFF38BDF8)
val PastelSkyLightText = Color(0xFF0C4A6E)
val PastelSkyLightTextSec = Color(0xFF0369A1)

val PastelSkyDarkBg = Color(0xFF0B1724)
val PastelSkyDarkSurface = Color(0xFF122336)
val PastelSkyDarkElevated = Color(0xFF1B324D)
val PastelSkyDarkBorder = Color(0xFF2B4E76)
val PastelSkyDarkPrimary = Color(0xFF7DD3FC)
val PastelSkyDarkAccent = Color(0xFF93C5FD)
val PastelSkyDarkText = Color(0xFFF0F9FF)
val PastelSkyDarkTextSec = Color(0xFFBAE6FD)

// 6. Pastel Butter (Lemon Chiffon)
val PastelButterLightBg = Color(0xFFFEFCE8)
val PastelButterLightSurface = Color(0xFFFFFFFF)
val PastelButterLightElevated = Color(0xFFFEF9C3)
val PastelButterLightBorder = Color(0xFFFEF08A)
val PastelButterLightPrimary = Color(0xFFEAB308)
val PastelButterLightAccent = Color(0xFFFACC15)
val PastelButterLightText = Color(0xFF713F12)
val PastelButterLightTextSec = Color(0xFFA16207)

val PastelButterDarkBg = Color(0xFF1A1809)
val PastelButterDarkSurface = Color(0xFF282410)
val PastelButterDarkElevated = Color(0xFF383316)
val PastelButterDarkBorder = Color(0xFF574E23)
val PastelButterDarkPrimary = Color(0xFFFDE047)
val PastelButterDarkAccent = Color(0xFFFEF08A)
val PastelButterDarkText = Color(0xFFFEFCE8)
val PastelButterDarkTextSec = Color(0xFFFDE047)

// 7. Pastel Matcha (Pistachio Cream)
val PastelMatchaLightBg = Color(0xFFF5F8F0)
val PastelMatchaLightSurface = Color(0xFFFFFFFF)
val PastelMatchaLightElevated = Color(0xFFE7EED9)
val PastelMatchaLightBorder = Color(0xFFCFDFC0)
val PastelMatchaLightPrimary = Color(0xFF65A30D)
val PastelMatchaLightAccent = Color(0xFF84CC16)
val PastelMatchaLightText = Color(0xFF365314)
val PastelMatchaLightTextSec = Color(0xFF4D7C0F)

val PastelMatchaDarkBg = Color(0xFF12180C)
val PastelMatchaDarkSurface = Color(0xFF1C2614)
val PastelMatchaDarkElevated = Color(0xFF27361C)
val PastelMatchaDarkBorder = Color(0xFF3E542D)
val PastelMatchaDarkPrimary = Color(0xFFBEF264)
val PastelMatchaDarkAccent = Color(0xFFD9F99D)
val PastelMatchaDarkText = Color(0xFFF7FEE7)
val PastelMatchaDarkTextSec = Color(0xFFBEF264)
